services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: poc_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - JWT_SECRET=${JWT_SECRET}
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL:-admin@luma.com}
      - DEFAULT_ADMIN_NAME=${DEFAULT_ADMIN_NAME:-Admin}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-123456}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG=0
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        # En producción o local, podemos apuntar directamente al backend
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000/api/v1}
    container_name: poc_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
