"""initial tables

Revision ID: adb76cf28f92
Revises: 
Create Date: 2026-06-04 10:16:16.669523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb76cf28f92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('proyecto_id', sa.String(), nullable=False),
    sa.Column('sprint_id', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyectos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('proyecto_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.String(), nullable=True),
    sa.Column('fecha_fin', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas_tecnicas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('historia_id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas_tecnicas')
    op.drop_table('sprints')
    op.drop_table('proyectos')
    op.drop_table('historias')
    # ### end Alembic commands ###
